In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv("diabetes.csv")

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.tail(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
col_names=["pregnancies","glucose","BP","skin","insulin","BMI","DiabetesPedigree","age","output"]

In [8]:
new_df=pd.read_csv('diabetes.csv',names=col_names)
new_df

,pregnancies,glucose,BP,skin,insulin,BMI,DiabetesPedigree,age,output
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0
...,...,...,...,...,...,...,...,...,...
764,10,101,76,48,180,32.9,0.171,63,0
765,2,122,70,27,0,36.8,0.34,27,0
766,5,121,72,23,112,26.2,0.245,30,0
767,1,126,60,0,0,30.1,0.349,47,1
768,1,93,70,31,0,30.4,0.315,23,0

In [9]:
new_df.columns

Index(['pregnancies', 'glucose', 'BP', 'skin', 'insulin', 'BMI',
       'DiabetesPedigree', 'age', 'output'],
      dtype='object')

In [10]:
new_df=new_df.iloc[1:]
new_df

    pregnancies glucose  BP skin insulin   BMI DiabetesPedigree age output
1             6     148  72   35       0  33.6            0.627  50      1
2             1      85  66   29       0  26.6            0.351  31      0
3             8     183  64    0       0  23.3            0.672  32      1
4             1      89  66   23      94  28.1            0.167  21      0
5             0     137  40   35     168  43.1            2.288  33      1
..          ...     ...  ..  ...     ...   ...              ...  ..    ...
764          10     101  76   48     180  32.9            0.171  63      0
765           2     122  70   27       0  36.8             0.34  27      0
766           5     121  72   23     112  26.2            0.245  30      0
767           1     126  60    0       0  30.1            0.349  47      1
768           1      93  70   31       0  30.4            0.315  23      0

[768 rows x 9 columns]

In [17]:
cols=["pregnancies","glucose","BP","insulin","BMI","DiabetesPedigree","age"]
x=new_df[cols]
y=new_df.output

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.25, random_state=0)
print(x_train.shape,x_test.shape)

(576, 7) (192, 7)

In [19]:
x_train

    pregnancies glucose  BP insulin   BMI DiabetesPedigree age
763           9      89  62       0  22.5            0.142  33
128           1     118  58      94  33.3            0.261  23
565           0      91  80       0  32.4            0.601  27
376          12     140  82     325  39.2            0.528  58
664           9     145  80     130  37.9            0.637  40
..          ...     ...  ..     ...   ...              ...  ..
764          10     101  76     180  32.9            0.171  63
193           7     159  66       0  30.4            0.383  36
630           4      94  65       0  24.7            0.148  21
560          11      85  74       0  30.1              0.3  35
685           5     136  82       0     0             0.64  69

[576 rows x 7 columns]

In [20]:
y_train

763    0
128    0
565    0
376    1
664    1
      ..
764    0
193    1
630    0
560    0
685    0
Name: output, Length: 576, dtype: object

In [21]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

c:\python 3.7\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression()

In [22]:
y_pred=logreg.predict(x_test)
y_pred

array(['1', '0', '0', '1', '0', '0', '1', '1', '0', '0', '1', '1', '0',
       '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '1', '1',
       '1', '1', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0',
       '0', '0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '0', '0', '1', '0', '1', '1', '0',
       '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0',
       '1', '0', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1',
       '0', '1', '1', '0', '1', '0', '0', '0', '0', '0'], dtype=object)

In [23]:
y_test

662    1
123    0
114    0
15     1
530    0
      ..
367    1
302    1
383    0
141    0
464    0
Name: output, Length: 192, dtype: object

In [25]:
for i,j in zip(y_test,y_pred):
    print(i,j)

1 1
0 0
0 0
1 1
0 0
0 0
1 1
1 1
0 0
0 0
1 1
1 1
0 0
0 0
0 0
0 0
1 1
0 0
0 0
0 0
1 1
1 0
0 0
0 0
0 0
0 0
0 0
0 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 1
1 0
0 0
0 0
0 1
0 0
0 0
0 0
1 1
1 1
0 0
0 0
1 0
1 0
1 0
0 0
0 0
1 1
0 0
0 0
0 0
0 0
1 1
1 0
1 0
1 1
0 0
0 0
1 1
1 1
1 1
1 1
0 0
0 0
0 0
0 0
0 0
0 0
0 1
1 1
0 0
0 0
0 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
1 1
0 0
0 0
0 0
0 0
0 0
0 1
0 0
1 0
0 1
1 1
1 0
0 0
0 0
0 0
0 0
0 1
1 0
0 0
0 0
0 0
1 1
0 0
1 0
1 1
1 0
1 1
1 1
0 0
0 1
0 0
1 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 1
0 0
0 0
0 0
0 0
1 1
0 0
1 0
0 0
1 0
1 1
0 0
0 0
0 1
0 0
0 0
1 0
0 0
0 0
0 0
0 0
1 0
0 0
1 1
0 0
0 0
1 1
0 0
0 1
0 0
1 1
1 1
1 1
1 1
0 0
0 0
0 1
1 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
1 0
0 1
0 0
0 0
0 0
0 0
0 0
1 0
1 1
0 0
1 1
1 1
0 0
1 1
1 0
1 0
0 0
0 0
0 0

In [27]:
from sklearn import metrics

In [28]:
print("Accurracy",metrics.accuracy_score(y_test,y_pred))

Accurracy 0.8072916666666666